### ISSUE TITLE
Pytest не видит модуль в папке /app

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/HW04_Zodiac#1]
@corsar, приветствую! Помогите разобраться, пожалуйста.

lib.py и main.py лежат в папке /app
Импортирую:
`from app.lib import get_zodiac_sign_number`
pytest отвечает
`    from app.lib import get_zodiac_sign_number
E   ModuleNotFoundError: No module named 'app'
`
Doctest отдельно при этом проходит

Если импортирую как 
`from lib import get_zodiac_sign_number`
То всё ОК
Если запускаю как 
`python -m pytest -v`
То всё ОК

Что пробовал:
пересоздавал venv 
Интерпретатор использую из venv
`pip remove pytest`
`pip install pytest`

Ничего пока не помогло.

**Comment by coursar** [comment]
app  должен быть пакетом (внутри должен быть файл __init__.py)
