### ISSUE TITLE
Является ли -1 валидным вводом?

### ISSUE THREAD

**Issue by coursar** [Lagunov-PRO/HW04_Zodiac#3]
https://github.com/Lagunov-PRO/HW04_Zodiac/blob/cc552664dd7ff256c61216bc70564182286bccdd/app/lib.py#L64-L65

**Comment by Lagunov-PRO** [comment]
Да, является, т.к. функция get_zodiac_sign_number(day, month) при аргументах, например (3, 19) возвращает нам (-1), т.е. индекс последнего элемента листа.

https://github.com/Lagunov-PRO/HW04_Zodiac/blob/cc552664dd7ff256c61216bc70564182286bccdd/app/lib.py#L32-L36

**Comment by coursar** [comment]
Я к тому, что логически значение -1 не является валидным

**Comment by Lagunov-PRO** [comment]
@coursar 
Переписал!
Хотя, если честно, совсем не интуитивно, почему -1 % 3 = 2 
https://github.com/Lagunov-PRO/HW04_Zodiac/blob/257ddb6a707f0b65619c27e2bf0aed00ada359d3/app/lib.py#L16-L19

**Comment by coursar** [comment]
это верно ))
