### ISSUE TITLE
Перепишите без else

### ISSUE THREAD

**Issue by coursar** [Lagunov-PRO/HW04_Zodiac#4]
https://github.com/Lagunov-PRO/HW04_Zodiac/blob/cc552664dd7ff256c61216bc70564182286bccdd/app/lib.py#L33-L36

**Comment by Lagunov-PRO** [comment]
Именно без else или без проверки второго условия?

https://github.com/Lagunov-PRO/HW04_Zodiac/commit/4efc32713074b95f6111629de87341f0f6dc173a

**Comment by Lagunov-PRO** [comment]
Ну собственно вторую проверку можно и не делать. Благодарю за подсказку!

https://github.com/Lagunov-PRO/HW04_Zodiac/commit/5b393e2d69dadba6693d136c1aa2aefd9a692301
