### ISSUE TITLE
Как исключить main() из codecov?

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/HW04_Zodiac#6]
@coursar Добавил объявление main()  как функции, теперь codecov ругается, что нет тестов. Как её исключить из проверки покрытия? Или как написать тест на функцию с пользовательским вводом?

**Comment by coursar** [comment]
написано в группе в vk ))

**Comment by Lagunov-PRO** [comment]
@coursar Как же фрагментирована информация у нас!
